version: '3'

services:
  postgres:
    image: 'postgres'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  foreman:
    build: .
    command: bundle exec foreman start
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
      - 'gems/:/gems'
  
  app:
    depends_on:
      - 'postgres'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
      - '3035:3035'
    volumes:
      - '.:/app'
      - 'gems/:/gems'

volumes:
  postgres:
  gems: